name: build

on: [push, pull_request]

jobs:
  build:
    name: Build (${{ matrix.toolchain }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, nightly]
    steps:
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          target: wasm32-unknown-unknown
          override: true
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install cargo-web
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-web
          version: latest
          use-tool-cache: true
      - name: cargo web build
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: web
          args: build --target=wasm32-unknown-unknown
      - name: cargo web build --all-features
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: web
          args: build --target=wasm32-unknown-unknown --all-features
