on: [push, pull_request]

name: check

jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-features -- -D warnings
      - run: cargo test --all-features
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-features -- -D warnings
      - run: cargo test --all-features
      # verify the docs build works using the same options used by the docs.rs build,
      # to surface any issues there before release
      - run: cargo doc --all-features --no-deps --config 'build.rustdocflags = ["--cfg", "docsrs", "-D", "warnings"]'
