on: [push, pull_request]

name: lint

jobs:
  lint:
    name: lint (${{ matrix.toolchain }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, nightly]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@${{ matrix.toolchain }}
      - run: cargo fmt --all -- --check
